export const AUDIO_UPLOAD_REQUEST = "AUDIO_UPLOAD_REQUEST";
export const AUDIO_UPLOAD_SUCCESS = "AUDIO_UPLOAD_SUCCESS";
export const AUDIO_UPLOAD_FAIL = "AUDIO_UPLOAD_FAIL";

export const AUDIO_LIST_REQUEST = "AUDIO_LIST_REQUEST";
export const AUDIO_LIST_SUCCESS = "AUDIO_LIST_SUCCESS";
export const AUDIO_LIST_FAIL = "AUDIO_LIST_FAIL";